/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package derechoHabiente;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 */
public class VerDatos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerDatos
     */
    private int id;

//    public VerDatos(int id) {
    public VerDatos() {

        initComponents();
//        this.id = id;
//        cargarDatos();

        Conexion con1 = new Conexion();
        Connection conet;
        DefaultTableModel modelo;
        Statement st;
        ResultSet rs;
        int idc;

                cajaCurp.setEnabled(false);

        cajaNombre.setEnabled(false);
        cajaAppa.setEnabled(false);
        cajaApma.setEnabled(false);
        cajaDia.setEnabled(false);
        cajaMes.setEnabled(false);
        cajaAño.setEnabled(false);
        cajaDireccion.setEnabled(false);
        cajaTelefono.setEnabled(false);
        cajaCorreo.setEnabled(false);
//                txtPrueba.setEnabled(false);

//        cajaNombre.setEnabled(false);
        btnListo.setVisible(false);

        txtId.setText("ID: "); 

    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtAppa = new javax.swing.JLabel();
        txtApma = new javax.swing.JLabel();
        txtEdad = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaAppa = new javax.swing.JTextField();
        cajaDia = new javax.swing.JTextField();
        cajaApma = new javax.swing.JTextField();
        cajaDireccion = new javax.swing.JTextField();
        cajaTelefono = new javax.swing.JTextField();
        txtEdad1 = new javax.swing.JLabel();
        txtEdad2 = new javax.swing.JLabel();
        cajaMes = new javax.swing.JTextField();
        cajaAño = new javax.swing.JTextField();
        btnActualizarDatos = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();
        cajaCurp = new javax.swing.JTextField();
        cajaCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Datos");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtId.setText("Curp");

        txtNombre.setText("Nombre: ");

        txtAppa.setText("Apellido Paterno:");

        txtApma.setText("Apellido Materno:");

        txtEdad.setText("Dia de nacimiento");

        txtDireccion.setText("Direccion:");

        jLabel7.setText("Telefono:");

        txtEdad1.setText("Mes de nacimiento");

        txtEdad2.setText("Año de nacimiento");

        btnActualizarDatos.setText("ActualizarDatos (Modificar)");
        btnActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDatosActionPerformed(evt);
            }
        });

        btnListo.setText("Listo");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        jLabel1.setText("Correo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtEdad2)
                                    .addGap(123, 123, 123))
                                .addComponent(txtAppa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtEdad)
                                    .addGap(128, 128, 128)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApma)
                                    .addComponent(txtEdad1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaMes, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(cajaApma)
                            .addComponent(cajaAppa)
                            .addComponent(cajaDia)
                            .addComponent(cajaAño, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaCurp)
                            .addComponent(cajaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnActualizarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addComponent(btnListo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cajaTelefono)
                            .addComponent(cajaDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(cajaCorreo))))
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtId))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(cajaCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre)
                            .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAppa)
                            .addComponent(cajaAppa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApma)
                            .addComponent(cajaApma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cajaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccion))
                                .addGap(18, 18, 18)
                                .addComponent(cajaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cajaCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnActualizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad)
                            .addComponent(cajaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad1)
                            .addComponent(cajaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad2)
                    .addComponent(cajaAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListo))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDatosActionPerformed

        cajaDireccion.setEnabled(true);
        cajaTelefono.setEnabled(true);
        cajaCorreo.setEnabled(true);

        btnListo.setVisible(true);
        btnActualizarDatos.setEnabled(false);


    }//GEN-LAST:event_btnActualizarDatosActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed

     
                cajaCorreo.setEnabled(false);

        cajaDireccion.setEnabled(false);
        cajaTelefono.setEnabled(false);
        btnActualizarDatos.setEnabled(true);

        btnListo.setVisible(false);


    }//GEN-LAST:event_btnListoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarDatos;
    private javax.swing.JButton btnListo;
    private javax.swing.JTextField cajaApma;
    private javax.swing.JTextField cajaAppa;
    private javax.swing.JTextField cajaAño;
    private javax.swing.JTextField cajaCorreo;
    private javax.swing.JTextField cajaCurp;
    private javax.swing.JTextField cajaDia;
    private javax.swing.JTextField cajaDireccion;
    private javax.swing.JTextField cajaMes;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtApma;
    private javax.swing.JLabel txtAppa;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtEdad;
    private javax.swing.JLabel txtEdad1;
    private javax.swing.JLabel txtEdad2;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables

    // Este método debe llamarse para cargar y mostrar los datos del derechohabiente
   public void cargarDatosDerechohabiente(String curpDerechohabiente) {
    Conexion con = new Conexion();
    Connection conn;
    Statement stmt;
    ResultSet rs;

    try {
        conn = con.getConnection();
        String sql = "SELECT * FROM derechohabiente WHERE curp = '" + curpDerechohabiente + "'";
        stmt = conn.createStatement();
        rs = stmt.executeQuery(sql);

        if (rs.next()) {
            cajaCurp.setText(rs.getString("curp"));
            cajaNombre.setText(rs.getString("nombre"));
            cajaAppa.setText(rs.getString("appa"));
            cajaApma.setText(rs.getString("apma"));
            cajaDia.setText(String.valueOf(rs.getInt("dia")));
            cajaMes.setText(String.valueOf(rs.getInt("mes")));
                cajaAño.setText(String.valueOf(rs.getInt("año")));
            cajaDireccion.setText(rs.getString("direccion"));
            cajaTelefono.setText(rs.getString("telefono"));
            cajaCorreo.setText(rs.getString("correo"));
        } else {
            JOptionPane.showMessageDialog(this, "El derechohabiente no fue encontrado");
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
   
   public void cargarDatosModerador(String curpModerador) {
    Conexion con = new Conexion();
    Connection conn;
    Statement stmt;
    ResultSet rs;

    try {
        conn = con.getConnection();
        String sql = "SELECT * FROM moderadores WHERE curp = '" + curpModerador + "'";
        stmt = conn.createStatement();
        rs = stmt.executeQuery(sql);

        if (rs.next()) {
            cajaCurp.setText(rs.getString("curp"));
            cajaNombre.setText(rs.getString("nombre"));
            cajaAppa.setText(rs.getString("appa"));
            cajaApma.setText(rs.getString("apma"));
            cajaDia.setText(String.valueOf(rs.getInt("dia")));
            cajaMes.setText(String.valueOf(rs.getInt("mes")));
                cajaAño.setText(String.valueOf(rs.getInt("año")));
            cajaDireccion.setText(rs.getString("direccion"));
            cajaTelefono.setText(rs.getString("telefono"));
            cajaCorreo.setText(rs.getString("correo"));
        } else {
            JOptionPane.showMessageDialog(this, "El moderador no fue encontrado");
        }

        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
}
